name: sales
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  aveo_api:
    git:
      url: https://gitlab+deploy-token-1:VAP5EJzZ-hgGp8v_TaJ6@gitlab.aveosoft.com/aveo-mobile-products/aveoapi.git
      ref: master
  google_maps_flutter: ^2.2.5
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  intl: ^0.18.0
  fluttertoast: ^8.2.1
  permission_handler: ^10.2.0
  smooth_page_indicator: ^1.0.1
  background_location:
    git:
      url: https://github.com/Almoullim/background_location.git
      ref: master

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix: assets